DeviceFileEvents
| where (ActionType in~ ("FileCreated", "FileRenamed")) and FileName =~ "ntds.dit" and FolderPath matches regex "(?i)^(?:[a-z]:\\\\(?:users|windows\\\\temp|temp|perflogs|\\$recycle\\.bin)(?:\\\\|$)|\\\\\\\\[a-z0-9_-][^\\\\/:*?\"<>|\\r\\n]*\\\\[^\\\\/:*?\"<>|\\r\\n]+(?:\\\\|$))"
| project TimeGenerated, DeviceId, DeviceName, ActionType, FileName, FolderPath, SHA1, InitiatingProcessAccountName, InitiatingProcessFileName, InitiatingProcessFolderPath, InitiatingProcessCommandLine, ReportId
