DeviceProcessEvents
| where FileName =~ "bitsadmin.exe" and (ProcessCommandLine contains "http://" or ProcessCommandLine contains "https://") and ProcessCommandLine matches regex "(?i)\\s/(?:transfer|addfile)\\s+\\S"
| project TimeGenerated, Timestamp, DeviceId, DeviceName, AccountDomain, AccountName, AccountSid, InitiatingProcessFileName, FileName, ProcessVersionInfoOriginalFileName, FolderPath, ProcessCommandLine, ReportId
