DeviceProcessEvents
| where ((FileName in~ ("procdump.exe", "procdump64.exe", "procdump64a.exe")) or (ProcessVersionInfoOriginalFileName in~ ("procdump.exe", "procdump64.exe", "procdump64a.exe"))) and ProcessCommandLine matches regex "(?i)(?:^|\\s)\"?lsass(?:\\.exe)?\"?(?:\\s|$)"
| project TimeGenerated, Timestamp, DeviceId, DeviceName, AccountDomain, AccountName, AccountSid, InitiatingProcessFileName, FileName, ProcessVersionInfoOriginalFileName, FolderPath, ProcessCommandLine, ReportId
