DeviceProcessEvents
| where (FileName =~ "sc.exe" or ProcessVersionInfoOriginalFileName =~ "sc.exe") and ProcessCommandLine matches regex "(?i)^\\s*(?:\"[^\"]+\"|\\S+)\\s+\"?\\\\\\\\[^\\\\\\s\"]+\"?\\s+create\\s+\\S+"
| project TimeGenerated, Timestamp, DeviceId, DeviceName, AccountDomain, AccountName, AccountSid, InitiatingProcessFileName, FileName, ProcessVersionInfoOriginalFileName, FolderPath, ProcessCommandLine, ReportId
