AuditLogs
| where (OperationName =~ "Add delegated permission grant" and Result =~ "success") and TargetResources contains "RoleManagement.ReadWrite.Directory" and TargetResources contains "AllPrincipals"
| extend InitiatingUserPrincipalName = tostring(InitiatedBy.user.userPrincipalName)
| extend InitiatingAccountName = tostring(split(InitiatingUserPrincipalName, "@")[0])
| extend InitiatingAccountUPNSuffix = tostring(split(InitiatingUserPrincipalName, "@")[1])
| extend InitiatingUserId = tostring(InitiatedBy.user.id)
| extend InitiatingIPAddress = tostring(InitiatedBy.user.ipAddress)
| extend InitiatingApplicationId = tostring(InitiatedBy.app.appId)
| extend InitiatingApplicationName = tostring(InitiatedBy.app.displayName)
| extend TargetServicePrincipalId = tostring(TargetResources[0].id)
| extend TargetServicePrincipalName = tostring(TargetResources[0].displayName)
| project TimeGenerated, OperationName, InitiatingUserPrincipalName, InitiatingAccountName, InitiatingAccountUPNSuffix, InitiatingUserId, InitiatingIPAddress, InitiatingApplicationId, InitiatingApplicationName, TargetServicePrincipalId, TargetServicePrincipalName, CorrelationId, LoggedByService
