DeviceProcessEvents
| where (FileName =~ "certutil.exe" or ProcessVersionInfoOriginalFileName =~ "certutil.exe") and ProcessCommandLine matches regex "(?i)(?:^|\\s)[/-]decode(?:hex)?\\s+\\S+"
| project TimeGenerated, Timestamp, DeviceId, DeviceName, AccountDomain, AccountName, AccountSid, InitiatingProcessFileName, FileName, ProcessVersionInfoOriginalFileName, FolderPath, ProcessCommandLine, ReportId
