DeviceProcessEvents
| where ((FileName in~ ("mavinject.exe", "mavinject64.exe")) or (ProcessVersionInfoOriginalFileName in~ ("mavinject.exe", "mavinject64.exe"))) and ProcessCommandLine matches regex "(?i)(?:^|\\s)/(?:INJECTRUNNING(?:\\s|$)|HMODULE(?:=|\\s))"
| project TimeGenerated, Timestamp, DeviceId, DeviceName, AccountDomain, AccountName, AccountSid, InitiatingProcessFileName, FileName, ProcessVersionInfoOriginalFileName, FolderPath, ProcessCommandLine, ReportId
