DeviceProcessEvents
| where FileName =~ "certutil.exe" and (ProcessCommandLine contains "http://" or ProcessCommandLine contains "https://" or ProcessCommandLine contains "ftp://") and ProcessCommandLine matches regex "(?i)\\s[-/]urlcache(?:\\s|$)" and ProcessCommandLine matches regex "(?i)\\s[-/]f(?:\\s|$)" and (not(ProcessCommandLine matches regex "(?i)\\sdelete\\s*$"))
| project TimeGenerated, Timestamp, DeviceId, DeviceName, AccountDomain, AccountName, AccountSid, InitiatingProcessFileName, FileName, ProcessVersionInfoOriginalFileName, FolderPath, ProcessCommandLine, ReportId
