DeviceProcessEvents
| where FileName =~ "reg.exe" and (ProcessCommandLine contains " save " or ProcessCommandLine contains " export ") and (ProcessCommandLine contains "HKLM\\SAM" or ProcessCommandLine contains "HKEY_LOCAL_MACHINE\\SAM" or ProcessCommandLine contains "HKLM\\SECURITY" or ProcessCommandLine contains "HKEY_LOCAL_MACHINE\\SECURITY")
| project TimeGenerated, Timestamp, DeviceId, DeviceName, AccountDomain, AccountName, AccountSid, InitiatingProcessFileName, FileName, FolderPath, ProcessCommandLine, ReportId
