DeviceProcessEvents
| where FileName =~ "certutil.exe" and (ProcessCommandLine contains "http://" or ProcessCommandLine contains "https://" or ProcessCommandLine contains "ftp://") and (ProcessCommandLine contains "-urlcache" or ProcessCommandLine contains "/urlcache" or ProcessCommandLine contains "-split" or ProcessCommandLine contains "/split")
| project TimeGenerated, Timestamp, DeviceId, DeviceName, AccountDomain, AccountName, AccountSid, InitiatingProcessFileName, FileName, FolderPath, ProcessCommandLine, ReportId
