DeviceProcessEvents
| where FileName =~ "bitsadmin.exe" and (ProcessCommandLine contains "http://" or ProcessCommandLine contains "https://") and (ProcessCommandLine contains "/transfer" or (ProcessCommandLine contains "/create" and ProcessCommandLine contains "/addfile"))
| project TimeGenerated, Timestamp, DeviceId, DeviceName, AccountDomain, AccountName, AccountSid, InitiatingProcessFileName, FileName, FolderPath, ProcessCommandLine, ReportId
