DeviceProcessEvents
| where (FileName =~ "auditpol.exe" or ProcessVersionInfoOriginalFileName =~ "auditpol.exe") and (ProcessCommandLine matches regex "(?i)(?:^|\\s)/clear(?:\\s|$)" or (ProcessCommandLine matches regex "(?i)(?:^|\\s)/remove(?:\\s|$)" and ProcessCommandLine matches regex "(?i)(?:^|\\s)/allusers(?:\\s|$)"))
| project TimeGenerated, Timestamp, DeviceId, DeviceName, AccountDomain, AccountName, AccountSid, InitiatingProcessFileName, FileName, ProcessVersionInfoOriginalFileName, FolderPath, ProcessCommandLine, ReportId
