DeviceProcessEvents
| where FileName =~ "regsvr32.exe" and ProcessCommandLine matches regex "(?i)(^|\\s)[/-]i(?:[:\\s]|$)" and (ProcessCommandLine contains "http://" or ProcessCommandLine contains "https://" or ProcessCommandLine contains "ftp://")
| project TimeGenerated, Timestamp, DeviceId, DeviceName, AccountDomain, AccountName, AccountSid, InitiatingProcessFileName, FileName, ProcessVersionInfoOriginalFileName, FolderPath, ProcessCommandLine, ReportId
