DeviceProcessEvents
| where (FileName =~ "odbcconf.exe" or ProcessVersionInfoOriginalFileName =~ "odbcconf.exe") and ProcessCommandLine matches regex "(?i)\\{\\s*REGSVR\\s+(?:\"[^\"]+\"|[^\\s\"}]+)(?:\\s|\\})"
| project TimeGenerated, Timestamp, DeviceId, DeviceName, AccountDomain, AccountName, AccountSid, InitiatingProcessFileName, FileName, ProcessVersionInfoOriginalFileName, FolderPath, ProcessCommandLine, ReportId
