AuditLogs
| where (OperationName in~ ("Add owner to application", "Add owner to service principal")) and Result =~ "success"
| extend InitiatingUserPrincipalName = tostring(InitiatedBy.user.userPrincipalName)
| extend InitiatingAccountName = tostring(split(InitiatingUserPrincipalName, "@")[0])
| extend InitiatingAccountUPNSuffix = tostring(split(InitiatingUserPrincipalName, "@")[1])
| extend InitiatingUserId = tostring(InitiatedBy.user.id)
| extend InitiatingIPAddress = tostring(InitiatedBy.user.ipAddress)
| extend InitiatingApplicationId = tostring(InitiatedBy.app.appId)
| extend InitiatingApplicationName = tostring(InitiatedBy.app.displayName)
| extend TargetApplicationObjectId = tostring(TargetResources[0].id)
| extend TargetApplicationName = tostring(TargetResources[0].displayName)
| project TimeGenerated, OperationName, InitiatingUserPrincipalName, InitiatingAccountName, InitiatingAccountUPNSuffix, InitiatingUserId, InitiatingIPAddress, InitiatingApplicationId, InitiatingApplicationName, TargetApplicationObjectId, TargetApplicationName, CorrelationId, LoggedByService
