AWSCloudTrail
| where EventSource =~ "guardduty.amazonaws.com" and EventName =~ "DeleteDetector" and EventTypeName =~ "AwsApiCall" and ManagementEvent =~ true and ReadOnly =~ false and ErrorCode =~ "" and ErrorMessage =~ ""
| project TimeGenerated, EventSource, EventName, EventTypeName, ManagementEvent, ReadOnly, ErrorCode, ErrorMessage, AWSRegion, SourceIpAddress, UserIdentityType, UserIdentityArn, RecipientAccountId, AwsEventId
