DeviceProcessEvents
| where (FileName in~ ("powershell.exe", "pwsh.exe")) and ProcessCommandLine matches regex "(?i)(^|\\s)[-/](?:e|ec|en|enc|enco|encod|encode|encoded|encodedc|encodedco|encodedcom|encodedcomm|encodedcomma|encodedcomman|encodedcommand)\\s+\"?[a-z0-9+/]+={0,2}(?:\"|\\s|$)"
| project TimeGenerated, Timestamp, DeviceId, DeviceName, AccountDomain, AccountName, AccountSid, InitiatingProcessFileName, FileName, ProcessVersionInfoOriginalFileName, FolderPath, ProcessCommandLine, ReportId
