DeviceProcessEvents
| where FileName =~ "regsvr32.exe" and (ProcessCommandLine contains " /i" or ProcessCommandLine contains " -i") and (ProcessCommandLine contains "http://" or ProcessCommandLine contains "https://" or ProcessCommandLine contains "ftp://")
| project TimeGenerated, Timestamp, DeviceId, DeviceName, AccountDomain, AccountName, AccountSid, InitiatingProcessFileName, FileName, FolderPath, ProcessCommandLine, ReportId
