DeviceProcessEvents
| where (FileName =~ "InstallUtil.exe" or ProcessVersionInfoOriginalFileName =~ "InstallUtil.exe") and ProcessCommandLine matches regex "(?i)(?:^|\\s)\"?(?:https?|ftp)://[^\\s\"]+"
| project TimeGenerated, Timestamp, DeviceId, DeviceName, AccountDomain, AccountName, AccountSid, InitiatingProcessFileName, FileName, ProcessVersionInfoOriginalFileName, FolderPath, ProcessCommandLine, ReportId
